version: '3'
services:
  mongodb:
    image: mongo 
  redis:
    image: redis
  deregnet-rest:
    image: sebwink/deregnet-rest:dev
    build: 
      context: ../..
      dockerfile: ./docker/Dockerfile
    environment:
      ENV: DEV
      DEBUG: 'true'
    volumes:
      - './server:/server'
    depends_on:
      - 'mongodb'
      - 'redis'
    links:
      - 'mongodb'
      - 'redis'
    ports:
            - "8080:8080"
