version: '3'
services:
  mongodb:
    image: mongo 
  redis:
    image: redis
    #clinvap_example_data:
    #  image: clinvap/report_db_api_example_data
    #depends_on:
    #  - 'clinvap_db'
    #links:
    #  - 'clinvap_db:db'
    #clinvap:
    #image: clinvap/report_db_api
    #depends_on:
    #  - 'clinvap_example_data'
    #links: 
    #  - 'clinvap_db:db'
  deregnet-rest:
    image: sebwink/deregnet-rest
    build: .
    environment:
      ENV: DEV
      DEBUG: 'true'
    volumes:
      - './server:/server'
    depends_on:
      - 'mongodb'
      - 'redis'
    links:
      - 'mongodb'
      - 'redis'
    ports:
            - "${DEREGNET_PORT}:8080"
