version: "3"
services:
  db:
    image: mongo
  kong-auth:
    image: sebwink/kong-auth 
    build: .
    env_file:
      - './.env'
    volumes:
      - '.:/app'
    depends_on:
      - db
    ports:
      - '5000:5000/tcp'
